name: Gatling Load Testing Example

on: [push]

jobs:
  validation:
    runs-on: ubuntu-latest
    container:
      image: gradle:jdk17
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1.0.4
  build:
    runs-on: ubuntu-latest
    container:
      image: gradle:jdk17
    steps:
      - uses: actions/checkout@v3

      - name: Make ./gradlew executable
        run: chmod +x ./gradlew

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2.1.5
        env:
          CI: true
        with:
          arguments: build

      - name: Execute Gatling
        run: ./gradlew gatlingRun
