name: Gatling JSON Placeholder Load Testing

on: [push]

jobs:
  validation:
    runs-on: ubuntu-latest
    container:
      image: gradle:jdk17
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
  build:
    runs-on: ubuntu-latest
    container:
      image: gradle:jdk17
    steps:
      - uses: actions/checkout@v4

      - name: Make ./gradlew executable
        run: chmod +x ./gradlew

      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2
        env:
          CI: true
        with:
          arguments: build

      - name: Execute Gatling
        run: ./gradlew gatlingRun
